### ISSUE TITLE
Add config option for working directory

### ISSUE THREAD

**Issue by tuaris** [pmarino90/igniter#12]
Some applications need you to 'cd' into a directory before starting.

**Comment by pmarino90** [comment]
Hi @tuaris,
thnx for this! If I got that correctly you mean to have an option in the config file to change the current working directory other than the one where the the config file is, right? so that the application has a different directory as `cwd`. Fairly easy change to do and I think it would be useful.

**Comment by tuaris** [comment]
Yes that's it.
